"use client"

import Link from "next/link"
import { Button } from "@/components/ui/button"
import { NoiseBackground } from "@/components/noise-background"
import { GeometricShapes } from "@/components/geometric-shapes"
import { DecorativeElements } from "@/components/decorative-elements"

export default function TermsAndConditions() {
  return (
    <div className="min-h-screen bg-light text-dark overflow-hidden">
      <NoiseBackground />
      <GeometricShapes />
      <DecorativeElements />

      {/* Header */}
      <header className="container mx-auto py-6 px-4 flex items-center justify-between relative z-10">
        <div className="flex items-center gap-2">
          <div className="text-2xl font-bold tracking-tighter">
            <Link href="/">
              <span className="text-neon">explore</span>
            </Link>
          </div>
        </div>
        <Button
          variant="outline"
          className="border-neon text-neon hover:bg-neon hover:text-white transition-all cyber-button"
          asChild
        >
          <Link href="/">Back to Home</Link>
        </Button>
      </header>

      <main className="container mx-auto px-4 py-12 relative z-10">
        <div className="max-w-4xl mx-auto bg-white/80 backdrop-blur-sm p-8 rounded-xl shadow-lg">
          <h1 className="text-4xl font-bold mb-8 text-center">Terms and Conditions for <span className="text-neon">Explore</span></h1>
          
          <p className="mb-6 text-sm text-gray-500">Last updated: April 03, 2025</p>
          
          <p className="mb-6">Please read these terms and conditions carefully before using Our Service.</p>
          
          <p className="mb-6">These Terms and Conditions ("Terms") govern your use of our web application (the "Service"). By accessing or using Explore, you agree to comply with these Terms. If you disagree, please do not use the Service.</p>
          
          <h2 className="text-2xl font-bold mt-8 mb-4">1. Definitions</h2>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li><strong>"Explore"</strong> refers to the web application developed by Explore, a company registered in Ukraine.</li>
            <li><strong>"User"</strong> refers to anyone accessing or using Explore.</li>
            <li><strong>"AI Companion"</strong> refers to the personalized AI-based assistant created by users within the Service.</li>
            <li><strong>"Voice Message"</strong> refers to audio input submitted by the user and audio responses generated by the AI.</li>
          </ul>
          
          <h2 className="text-2xl font-bold mt-8 mb-4">2. Eligibility</h2>
          <p className="mb-6">You must be at least 18 years old to use Explore. By using the Service, you confirm that you meet this requirement.</p>
          
          <h2 className="text-2xl font-bold mt-8 mb-4">3. User Accounts</h2>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li>You may need to create an account to access certain features of Explore.</li>
            <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
            <li>Users who violate these Terms (e.g., by engaging in hate speech) may be banned from using the Service.</li>
          </ul>
          
          <h2 className="text-2xl font-bold mt-8 mb-4">4. Acceptable Use</h2>
          <p className="mb-4">By using Explore, you agree <strong>not</strong> to:</p>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li>Use the Service for illegal, harmful, or abusive purposes.</li>
            <li>Share or create content that is hateful, discriminatory, or offensive.</li>
            <li>Attempt to gain unauthorised access to other user accounts or systems.</li>
            <li>Misrepresent your identity or impersonate others.</li>
          </ul>
          
          <h2 className="text-2xl font-bold mt-8 mb-4">5. Service Description</h2>
          <p className="mb-4">Explore is a web-based application that uses AI technology to help users practice English speaking skills. Users create AI companions and practice through voice messages. The user records a message, which is analyzed by AI, and receives a spoken response from the AI companion.</p>
          <p className="mb-6">Additionally, users can practice English via <strong>real-time calls</strong> with their AI companion, using Conversational AI technology. This feature enables more dynamic and interactive speaking practice sessions, simulating natural conversation flow.</p>
          
          <h2 className="text-2xl font-bold mt-8 mb-4">6. Subscription and Payments</h2>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li>Explore is offered as a Software-as-a-Service (SaaS) product.</li>
            <li>Users can access the Service via a monthly or annual subscription.</li>
            <li>We use <Link href="https://monobank.ua/plata-by-mono"><strong>Plata by Monobank</strong></Link> for processing payments.</li>
            <li>A 3-day free trial is available for new users.</li>
            <li>Refunds are available within 14 days of purchase.</li>
          </ul>
          
          <h2 className="text-2xl font-bold mt-8 mb-4">7. Data Usage and Privacy</h2>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li>User voice messages are stored indefinitely.</li>
            <li>We share data with third-party providers, including OpenAI and ElevenLabs, to process voice and generate AI responses.</li>
            <li>We do not use user data to train our AI models.</li>
            <li>Your use of Explore is also governed by our <Link href="/privacy-policy"><strong>Privacy Policy</strong></Link>, which explains how we collect, use, and protect your data.</li>
          </ul>
          
          <h2 className="text-2xl font-bold mt-8 mb-4">8. Account Deletion</h2>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li>Users may request to delete their account by contacting customer support.</li>
            <li>Upon deletion, all associated user data is erased immediately.</li>
            <li>Explore does not unilaterally terminate user access to accounts.</li>
          </ul>
          
          <h2 className="text-2xl font-bold mt-8 mb-4">9. Intellectual Property</h2>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li>All content, trademarks, and software within Explore are owned by Explore or licensed to us.</li>
            <li>You retain ownership of the content you create but grant us a non-exclusive license to use it to provide and improve the Service.</li>
          </ul>
          
          <h2 className="text-2xl font-bold mt-8 mb-4">10. Limitation of Liability</h2>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li>Explore is provided "as is" without guarantees of accuracy, reliability, or availability.</li>
            <li>We are not liable for any direct or indirect damages arising from your use of the Service.</li>
          </ul>
          
          <h2 className="text-2xl font-bold mt-8 mb-4">11. Governing Law</h2>
          <p className="mb-6">These Terms are governed by the laws of Ukraine. Any disputes shall be resolved in the appropriate courts of Ukraine.</p>
          
          <h2 className="text-2xl font-bold mt-8 mb-4">12. Support and Communication</h2>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li>For questions or issues, users can contact us via email, phone, or through messaging apps (Telegram, Viber, WhatsApp) using the contact details on our website.</li>
            <li>We do not guarantee a specific response time.</li>
          </ul>
          
          <h2 className="text-2xl font-bold mt-8 mb-4">13. Changes to These Terms</h2>
          <p className="mb-6">We may update these Terms from time to time. Continued use of Explore after updates constitutes acceptance of the revised Terms.</p>
          
          <h2 className="text-2xl font-bold mt-8 mb-4">14. Contact Us</h2>
          <p className="mb-6">For questions or concerns, contact us using the contact information provided on our website.</p>
          
          <p className="mt-8 mb-6">By using Explore, you acknowledge that you have read and agree to these Terms and Conditions.</p>
        </div>
      </main>

      <footer className="py-12 relative z-10">
        <div className="container mx-auto px-4">
          <div className="flex flex-col md:flex-row justify-between items-center">
            <div className="text-2xl font-bold tracking-tighter mb-4 md:mb-0">
              <Link href="/">
                <span className="text-neon">explore</span>
              </Link>
            </div>
            <div className="flex gap-6">
              <div className="text-sm text-medium">© {new Date().getFullYear()} Explore. All rights reserved.</div>
              <div className="flex gap-6">
                <Link href="/privacy-policy" className="text-sm text-medium hover:text-neon transition-colors">
                  Privacy Policy
                </Link>
                <Link href="/terms-conditions" className="text-sm text-medium hover:text-neon transition-colors">
                  Terms & Conditions
                </Link>
              </div>
            </div>
          </div>
        </div>
      </footer>
    </div>
  )
} 